// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuaqlHQWyvaFKNt2ZzDL0HIeTBHM6se_4',
    appId: '1:254509162866:web:53bab5c317cc71cb7cbdeb',
    messagingSenderId: '254509162866',
    projectId: 'nawa-730d1',
    authDomain: 'nawa-730d1.firebaseapp.com',
    storageBucket: 'nawa-730d1.appspot.com',
    measurementId: 'G-B1X1P92J56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRM7c3VcUWgHEDj7s1Dh5sEZMhTWEoQuM',
    appId: '1:254509162866:android:73aae37a39e1022d7cbdeb',
    messagingSenderId: '254509162866',
    projectId: 'nawa-730d1',
    storageBucket: 'nawa-730d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrtHBOvzXwmJBiJbIjQk9IUqKW6YJtN0',
    appId: '1:254509162866:ios:cd421f61e6da9d517cbdeb',
    messagingSenderId: '254509162866',
    projectId: 'nawa-730d1',
    storageBucket: 'nawa-730d1.appspot.com',
    iosClientId:
        '254509162866-f3vdm3a93qe70r8s46ihh990tbbvcuss.apps.googleusercontent.com',
    iosBundleId: 'com.example.nawaForWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrtHBOvzXwmJBiJbIjQk9IUqKW6YJtN0',
    appId: '1:254509162866:ios:cd421f61e6da9d517cbdeb',
    messagingSenderId: '254509162866',
    projectId: 'nawa-730d1',
    storageBucket: 'nawa-730d1.appspot.com',
    iosClientId:
        '254509162866-f3vdm3a93qe70r8s46ihh990tbbvcuss.apps.googleusercontent.com',
    iosBundleId: 'com.example.nawaForWeb',
  );
}
